spring:
  application:
    name: medibug
  datasource:
    url: ${DATABASE_POSTGRESQL_URL}
    username: ${DATABASE_POSTGRESQL_USERNAME}
    password: ${DATABASE_POSTGRESQL_PASSWORD}

## Telemetry
management:
  otlp:
    metrics:
      export:
        enabled: false   # desactiva OTLP para evitar el crash por protobuf mientras alineas versiones
  influx:
    metrics:
      export:
        enabled: false   # opcional: evita intentos de conectar a Influx de Micrometer si no está arriba

## Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.boot.autoconfigure: INFO
    io.micrometer: DEBUG
    io.opentelemetry: DEBUG
    uni.csw.medibug: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n"

## Influx para IoT
influxdb:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  database: ${INFLUX_DB}

## MQTT
mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: medibug-client

